import type { Struttura } from "./types";

/**
 * DATI DIMOSTRATIVI — nessuna di queste strutture esiste.
 * Servono solo a far girare le pagine finché non arriva l'import dei dati reali
 * (open data regionali + Google Places). Tutti i record hanno `fonte_dati: "demo"`
 * e l'avviso viene mostrato in pagina: vedi src/components/AvvisoDemo.tsx.
 */
export const STRUTTURE_DEMO: Struttura[] = [
  {
    nome: "RSA Villa Aurora (esempio)",
    slug: "rsa-villa-aurora-milano",
    tipologia: "rsa",
    indirizzo: "Via Esempio 12",
    cap: "20139",
    comune: "Milano",
    provincia: "Milano",
    provincia_sigla: "MI",
    regione: "Lombardia",
    lat: 45.4408,
    lng: 9.2093,
    telefono: "+39 02 0000001",
    email: "info@esempio-villaaurora.it",
    sito_web: "https://www.esempio-villaaurora.it",
    posti_letto: 120,
    convenzionata: true,
    nucleo_alzheimer: true,
    prezzo_min: 2200,
    prezzo_max: 3100,
    descrizione:
      "Residenza sanitaria assistenziale con nucleo Alzheimer dedicato, servizio infermieristico 24 ore su 24 e ampio giardino interno.",
    fonte_dati: "demo",
    updated_at: "2026-08-01T00:00:00.000Z",
  },
  {
    nome: "RSA Il Glicine (esempio)",
    slug: "rsa-il-glicine-milano",
    tipologia: "rsa",
    indirizzo: "Viale Dimostrativo 4",
    cap: "20154",
    comune: "Milano",
    provincia: "Milano",
    provincia_sigla: "MI",
    regione: "Lombardia",
    lat: 45.4842,
    lng: 9.1712,
    telefono: "+39 02 0000002",
    email: "info@esempio-ilglicine.it",
    sito_web: null,
    posti_letto: 84,
    convenzionata: true,
    nucleo_alzheimer: false,
    prezzo_min: 2000,
    prezzo_max: 2600,
    descrizione:
      "Struttura accreditata nel quartiere Sempione, con fisioterapia interna e percorsi di riabilitazione post-ospedaliera.",
    fonte_dati: "demo",
    updated_at: "2026-08-01T00:00:00.000Z",
  },
  {
    nome: "Casa di Riposo San Martino (esempio)",
    slug: "casa-di-riposo-san-martino-milano",
    tipologia: "casa-di-riposo",
    indirizzo: "Via Prova 88",
    cap: "20126",
    comune: "Milano",
    provincia: "Milano",
    provincia_sigla: "MI",
    regione: "Lombardia",
    lat: 45.5139,
    lng: 9.2201,
    telefono: "+39 02 0000003",
    email: null,
    sito_web: null,
    posti_letto: 60,
    convenzionata: false,
    nucleo_alzheimer: false,
    prezzo_min: 1700,
    prezzo_max: 2200,
    descrizione:
      "Casa di riposo per anziani autosufficienti e parzialmente autosufficienti, con animazione quotidiana e camere singole.",
    fonte_dati: "demo",
    updated_at: "2026-08-01T00:00:00.000Z",
  },
  {
    nome: "Centro Diurno Integrato Le Betulle (esempio)",
    slug: "centro-diurno-le-betulle-milano",
    tipologia: "centro-diurno",
    indirizzo: "Via Campione 7",
    cap: "20132",
    comune: "Milano",
    provincia: "Milano",
    provincia_sigla: "MI",
    regione: "Lombardia",
    lat: 45.5011,
    lng: 9.2565,
    telefono: "+39 02 0000004",
    email: "info@esempio-lebetulle.it",
    sito_web: null,
    posti_letto: 30,
    convenzionata: true,
    nucleo_alzheimer: true,
    prezzo_min: 45,
    prezzo_max: 70,
    descrizione:
      "Centro diurno integrato aperto dal lunedì al venerdì, con trasporto dedicato e attività di stimolazione cognitiva.",
    fonte_dati: "demo",
    updated_at: "2026-08-01T00:00:00.000Z",
  },
  {
    nome: "Assistenza Domiciliare CuraSerena (esempio)",
    slug: "assistenza-domiciliare-curaserena-milano",
    tipologia: "assistenza-domiciliare",
    indirizzo: "Via Modello 21",
    cap: "20122",
    comune: "Milano",
    provincia: "Milano",
    provincia_sigla: "MI",
    regione: "Lombardia",
    lat: 45.4612,
    lng: 9.1955,
    telefono: "+39 02 0000005",
    email: "info@esempio-curaserena.it",
    sito_web: "https://www.esempio-curaserena.it",
    posti_letto: null,
    convenzionata: true,
    nucleo_alzheimer: false,
    prezzo_min: 22,
    prezzo_max: 35,
    descrizione:
      "Servizio di assistenza domiciliare integrata con operatori socio-sanitari, infermieri e fisioterapisti a domicilio.",
    fonte_dati: "demo",
    updated_at: "2026-08-01T00:00:00.000Z",
  },
  {
    nome: "RSA Parco Verde (esempio)",
    slug: "rsa-parco-verde-sesto-san-giovanni",
    tipologia: "rsa",
    indirizzo: "Via Fittizia 3",
    cap: "20099",
    comune: "Sesto San Giovanni",
    provincia: "Milano",
    provincia_sigla: "MI",
    regione: "Lombardia",
    lat: 45.5333,
    lng: 9.2333,
    telefono: "+39 02 0000006",
    email: null,
    sito_web: null,
    posti_letto: 72,
    convenzionata: true,
    nucleo_alzheimer: true,
    prezzo_min: 1950,
    prezzo_max: 2500,
    descrizione:
      "RSA immersa nel verde alle porte di Milano, con nucleo dedicato alle demenze e ricoveri di sollievo temporanei.",
    fonte_dati: "demo",
    updated_at: "2026-08-01T00:00:00.000Z",
  },
  {
    nome: "Casa di Riposo Le Rondini (esempio)",
    slug: "casa-di-riposo-le-rondini-bergamo",
    tipologia: "casa-di-riposo",
    indirizzo: "Via Esemplare 15",
    cap: "24121",
    comune: "Bergamo",
    provincia: "Bergamo",
    provincia_sigla: "BG",
    regione: "Lombardia",
    lat: 45.6983,
    lng: 9.6773,
    telefono: "+39 035 000001",
    email: "info@esempio-lerondini.it",
    sito_web: null,
    posti_letto: 48,
    convenzionata: false,
    nucleo_alzheimer: false,
    prezzo_min: 1600,
    prezzo_max: 2100,
    descrizione:
      "Struttura a conduzione familiare in Città Alta, con cucina interna e assistenza continuativa diurna e notturna.",
    fonte_dati: "demo",
    updated_at: "2026-08-01T00:00:00.000Z",
  },
  {
    nome: "RSA Santa Chiara (esempio)",
    slug: "rsa-santa-chiara-torino",
    tipologia: "rsa",
    indirizzo: "Corso Dimostrativo 100",
    cap: "10128",
    comune: "Torino",
    provincia: "Torino",
    provincia_sigla: "TO",
    regione: "Piemonte",
    lat: 45.0578,
    lng: 7.6761,
    telefono: "+39 011 000001",
    email: "info@esempio-santachiara.it",
    sito_web: "https://www.esempio-santachiara.it",
    posti_letto: 96,
    convenzionata: true,
    nucleo_alzheimer: false,
    prezzo_min: 2100,
    prezzo_max: 2800,
    descrizione:
      "Residenza sanitaria assistenziale nel centro di Torino, convenzionata con il servizio sanitario regionale.",
    fonte_dati: "demo",
    updated_at: "2026-08-01T00:00:00.000Z",
  },
  {
    nome: "Centro Diurno La Meridiana (esempio)",
    slug: "centro-diurno-la-meridiana-torino",
    tipologia: "centro-diurno",
    indirizzo: "Via Campione 9",
    cap: "10135",
    comune: "Torino",
    provincia: "Torino",
    provincia_sigla: "TO",
    regione: "Piemonte",
    lat: 45.0301,
    lng: 7.6612,
    telefono: "+39 011 000002",
    email: null,
    sito_web: null,
    posti_letto: 25,
    convenzionata: true,
    nucleo_alzheimer: false,
    prezzo_min: 40,
    prezzo_max: 60,
    descrizione:
      "Centro diurno per anziani fragili con laboratori di memoria, ginnastica dolce e supporto ai familiari caregiver.",
    fonte_dati: "demo",
    updated_at: "2026-08-01T00:00:00.000Z",
  },
  {
    nome: "RSA Villa dei Tigli (esempio)",
    slug: "rsa-villa-dei-tigli-firenze",
    tipologia: "rsa",
    indirizzo: "Via Prova 45",
    cap: "50122",
    comune: "Firenze",
    provincia: "Firenze",
    provincia_sigla: "FI",
    regione: "Toscana",
    lat: 43.7696,
    lng: 11.2558,
    telefono: "+39 055 000001",
    email: "info@esempio-villadeitigli.it",
    sito_web: null,
    posti_letto: 64,
    convenzionata: true,
    nucleo_alzheimer: true,
    prezzo_min: 2050,
    prezzo_max: 2700,
    descrizione:
      "RSA accreditata con modulo Alzheimer, servizio di podologia e progetti assistenziali individuali.",
    fonte_dati: "demo",
    updated_at: "2026-08-01T00:00:00.000Z",
  },
  {
    nome: "Casa di Riposo Il Borgo (esempio)",
    slug: "casa-di-riposo-il-borgo-firenze",
    tipologia: "casa-di-riposo",
    indirizzo: "Via Fittizia 6",
    cap: "50143",
    comune: "Firenze",
    provincia: "Firenze",
    provincia_sigla: "FI",
    regione: "Toscana",
    lat: 43.7712,
    lng: 11.2338,
    telefono: "+39 055 000002",
    email: null,
    sito_web: null,
    posti_letto: 40,
    convenzionata: false,
    nucleo_alzheimer: false,
    prezzo_min: 1800,
    prezzo_max: 2300,
    descrizione:
      "Casa di riposo con camere singole e doppie, spazi comuni luminosi e assistenza personalizzata.",
    fonte_dati: "demo",
    updated_at: "2026-08-01T00:00:00.000Z",
  },
  {
    nome: "Assistenza Domiciliare Fiorentina (esempio)",
    slug: "assistenza-domiciliare-fiorentina-firenze",
    tipologia: "assistenza-domiciliare",
    indirizzo: "Viale Esempio 2",
    cap: "50136",
    comune: "Firenze",
    provincia: "Firenze",
    provincia_sigla: "FI",
    regione: "Toscana",
    lat: 43.7719,
    lng: 11.2861,
    telefono: "+39 055 000003",
    email: "info@esempio-adfiorentina.it",
    sito_web: null,
    posti_letto: null,
    convenzionata: false,
    nucleo_alzheimer: false,
    prezzo_min: 20,
    prezzo_max: 32,
    descrizione:
      "Assistenza domiciliare privata con operatori selezionati, gestione delle pratiche e supporto infermieristico su richiesta.",
    fonte_dati: "demo",
    updated_at: "2026-08-01T00:00:00.000Z",
  },
];
